### ISSUE TITLE
存在利用观战模式作弊的可能

### ISSUE THREAD

**Issue by Futrime** [eesast/THUAI6#291]
**Describe the bug**

如果在比赛过程中允许观战，则智能体端可以通过观战接口，获取全局信息，从而实现作弊。不知道你们有没有对这个情况进行防御。

**Expected behavior**

也许可以通过观战时需要token来解决。

**Comment by TCL606** [comment]
感谢你的提醒。或许可以设置server在正式比赛时不允许观战。 @gsy1519

**Comment by Timothy-Liuxf** [comment]
@gsy1519 加一个 `bool` 的命令行选项就可以（默认可以设为允许观战，为了保证和之前发布的脚本兼容）

**Comment by gsy1519** [comment]
有道理，已经修改并提pr了。
