### ISSUE TITLE
System.Threading.LockRecursionException: Recursive read lock acquisitions not allowed in this mode.

### ISSUE THREAD

**Issue by TCL606** [eesast/THUAI6#485]
**Describe the bug**
这里似乎以极小的概率报错：https://github.com/eesast/THUAI6/blob/b1b2904777fc2a22916de9e05cd6cd09c017e79e/logic/GameClass/GameObj/Map/Map.cs#L18
![bdcad0f14e60b515a149dbf8a49ac55](https://user-images.githubusercontent.com/84725343/235354305-f7063fcc-7334-40cc-a032-d96048441464.png)

**Additional context**
numOfDeceasedStudent 和 numOfEscapedStudent 的读写确实感觉怪怪的。

**Comment by Timothy-Liuxf** [comment]
根据报错信息来看，我觉得更像是这里出了问题：
https://github.com/eesast/THUAI6/blob/b1b2904777fc2a22916de9e05cd6cd09c017e79e/logic/GameClass/GameObj/Map/Map.cs#L26
或者是其他的进行了 `EnterReadLock` 等处
因为 C# 的读写锁和 `Monitor.Lock`（即 `lock` 关键字）不同，C# 的读写锁是不可重入的，在一个线程中如果已经 `EnterReadLock`，便不能再次 `EnterReadLock`，否则便会抛出此异常：
<https://learn.microsoft.com/zh-cn/dotnet/api/system.threading.lockrecursionexception?view=net-6.0>
