### ISSUE TITLE
关于 `EndAllAction` 的实现问题（光速学习、卡墙等）

### ISSUE THREAD

**Issue by Timothy-Liuxf** [eesast/THUAI6#488]
**Describe the bug**
现在的 `EndAllAction` 的实现逻辑有误，仅仅是改变了状态这个变量的值，却没有等待人物的状态真正地改变，从而导致穿墙（多重移动）、光速修机（多重修机）等多种 bug。

以移动为例，现在的停止状态代码：
https://github.com/eesast/THUAI6/blob/12aa0dec2abdeee8d866885911a71f5c5a65e73f/logic/GameClass/GameObj/Character/Character.cs#L324-L335
在停止移动时，仅仅是把 `IsMoving` 置为 `false`，试图来通知移动线程停止移动，这存在问题：
+ 首先，移动线程没有真的停止，因为需要等到移动线程下一轮判断 `IsMoving` 后才能退出，而此时移动线程可能还在行走一步，但是，`player` 的状态已经改变了，所以这一刻如果有移动的指令发来，就会导致又开启了一个移动线程，这会造成双重移动。本质上的原因是，状态转移并没有真的完成真正的状态转移，没有真的停止人物的移动状态。应当是先通知人物停止移动，然后等待移动线程停止移动，最后再更改人物的移动状态为不移动允许新一轮移动。
+ `IsMoving` 的职责是用来表征人物是否在移动的， 而不是控制人物是否该移动的，职责混乱。理论上 `IsMoving` 应当仅由控制移动的 `MoveManager` 来更改。

**To Reproduce**
选手群里已经有很多这种例子了（

**Expected behavior**
以移动为例（修机自行类比），一个解决方案如下（没好好起命名）：
给**每个可移动物体**加一个尽可以 `atomic` 访问的 `bool` 变量，设为 `flag`，默认是 `false`；，加一个锁 `mtx`
`MoveObj` 的时候

```c
void MoveObj()
{
        while (load(ref flag)) { 移动 }
    lock (mtx) {
        IsMoving = false;
        save(ref flag, false);
        Monitor.PulseAll(mtx);
    }
}

void StopMoving() {
    lock (mtx) {
        if (IsMoving) {
            save(ref flag, true);
            while (IsMoving) Monitor.Wait(mtx);
        }
    }
    SetStatus();
}
```

上述操作完全封装到移动引擎 `MoveManager` 中，`flag` 不要对外暴露。
这样，`flag` 仅用于通知移动线程停止移动，而 `IsMoving`

**Additional context**
之前在微信群写的有点错误，锁错了地方，现在改一下。。。

**Comment by Timothy-Liuxf** [comment]
@shangfengh

**Comment by shangfengh** [comment]
现在计划采用Semaphore来解决这个问题

**Comment by shangfengh** [comment]
现在已解决该问题
