### ISSUE TITLE
bug related to read/write lock in server 

### ISSUE THREAD

**Issue by thuchengyun21** [eesast/THUAI6#544]
**Describe the bug**
When running cpp version of players' code, the server might break down soon after the game starts. The timing of this seems to be in a random manner, sometimes not happening at all. As we're currently rewriting the entire .cpp file, we do not rule out multiple bugs in our own AI.cpp, but the info printed seems to point to a bug in Server. To ensure reproduction, please operate sevaral times.

**To Reproduce**
1. Open RunServer.cmd
2. Open RunCpp.cmd
3. Happens with or without opening RunGUIClient.cmd

**Expected behavior**
The server should print nothing during the course of the game ,except for new spectators.

**Screenshots**
![image](https://github.com/eesast/THUAI6/assets/89759247/ec29dd57-dc88-4148-8938-0e44035879e2)
and meanwhile in GUI:

![image](https://github.com/eesast/THUAI6/assets/89759247/884bdac9-e9bd-48bb-a2c3-d0a61f9c226b)

**Additional context**
I do not know whether this is related (perhaps we wrote erroneous commands in RunGUIClient.cmd), but the graphic interface refuse to open correctly if it is opened after RunCpp.cmd. The error feedback is as follows:
![image](https://github.com/eesast/THUAI6/assets/89759247/8c8ebede-3a6b-42c3-8018-d2d2edaffe71)

However, it will run correctly if opened after RunServer.cmd and before RunCpp.cmd. This does not interfere with actual programming ,but can be a little annoying.

**Comment by thuchengyun21** [comment]
I just learned that the first one will be solved in a new PR(issue already closed), but it did not seem to have anything to do with the second.

Additional info: I do not know whether this will be helpful : twice I observed the breakdown after a Student is hit.

**Comment by Timothy-Liuxf** [comment]
@shangfengh 看一看怎么回事

**Comment by Shawqeem** [comment]
[gh pr checkout 545](url) 在这个pr中第二个问题已被解决。
