### ISSUE TITLE
关于消息队列 `messageQueue`

### ISSUE THREAD

**Issue by Timothy-Liuxf** [eesast/THUAI6#64]
@DragonAura 
现在处理并发安全的方式，`messageQueue` 和它的锁 `messageMutex` 是分开的，这个不是很好维护，每用一次就好写一次上锁，还有忘记写的风险。最好把 `queue` 和 `mutex` 封装一下，封装成一个类，这样会比较好，可以参考一下这个实现：[https://github.com/eesast/THUAI5/blob/dev/CAPI/thuai/include/concurrent_queue.hpp](https://github.com/eesast/THUAI5/blob/dev/CAPI/thuai/include/concurrent_queue.hpp)
看了一下，里面的接口基本都可以直接拿来用

**Comment by DragonAura** [comment]
合理的，下周就改（×）

**Comment by Timothy-Liuxf** [comment]
@DragonAura 哦对，也许需要解释一下，那个里面的 `emplace` 接口是可以直接传构造函数的参数的（和 C++11 的规定保持一致），比如：
```c++
concurrent_queue<pair<int32_t, int32_t>> q;
q.emplace(114514, 1919810);  // 作用类似于 q.push(make_pair<int32_t, int32_t>(114514, 1919810));
```
