### ISSUE TITLE
关于C#多线程中值类型set访问器的误导性

### ISSUE THREAD

**Issue by shangfengh** [eesast/THUAI6#645]
**Describe the bug**

~~~csharp
private int hp = 0;
public int HP
{
  get
  {
    lock (gameObjLock)
    return hp;
  }
  set
  {
    lock (gameObjLock)
    hp = value;
  }
}
~~~

~~~csharp
private int hp = 0;
public int HP
{
  get => Interlocked.CompareExchange(ref hp, -1, -1);
  set => Interlocked.Exchange(ref hp, value);
}
~~~

在多线程中，通常要对set与get访问器加锁或采用原子操作保证安全，但是这并不能保证完全安全合理
例如`HP+=3;`就是显然的错误
其相当与先调用get，再调用set，中间插入set操作将导致结果错误

这样可能导致set访问器具有误导性

**Expected behavior**
目前我进行中的修改方法是单独编写set或add方法
clgg建议可以采用结构体/类的方式来解决

应当令`HP+=3;`的写法在语法上不成立或者能够安全地编译
这个问题应该并非没有先例，想知道有什么更优雅的解决方案

**Additional context**
[本issue与这个issue相关，但你不需要查看这个issue](https://github.com/eesast/THUAI6/issues/163)

**Comment by Timothy-Liuxf** [comment]
+= 确实不能保证原子。可以封装出一些方法来做诸如 `AddHp`。对于这点，C++ 的方案是封装成泛型类，比如原子的 `int` 就是 `std::atomic<int>`，一切操作否封装在它的成员函数内。

**Comment by shangfengh** [comment]
将采用结构体的方式解决该问题

**Comment by shangfengh** [comment]
改为使用类解决这个问题，结构体过于不便
